add missing french keys
witty-works/nlp_api pull request #1149
Opened 2024-09-18 09:41 UTC by lsmith77

fixes https://github.com/witty-works/nlp_api/issues/1148

2024-09-18 13:59 UTC, lsmith77 commented on app/main.py
> +translations = {
@barbaraWittyWorks we need translations for all of the below strings

2024-09-18 14:00 UTC, lsmith77 commented on app/main.py
> +        LangType.FR: "",
see also https://wittyworks.slack.com/archives/CTDRE2ATW/p1726665963787479

2024-09-19 06:29 UTC, barbaraWittyWorks requested changes

2024-09-19 06:29 UTC, barbaraWittyWorks commented on app/main.py
> +translations = {
```
@barbaraWittyWorks	Reply...
    RuleLabelEnum.BE_SPECIFIC: {
        LangType.EN: "Be specific",
        LangType.DE: "Sei spezifisch",
        LangType.FR: "Soyez spécifique",
    },
    RuleLabelEnum.NOT_FOR_PEOPLE: {
        LangType.EN: "Don't use this phrase for people",
        LangType.DE: "Nicht auf Menschen beziehen",
        LangType.FR: "N'utilisez pas ce terme pour les personnes",
    },
    RuleLabelEnum.NAME_DISABILITY: {
        LangType.EN: "Name the disability or condition",
        LangType.DE: "Nenne die Behinderung oder Zustand",
        LangType.FR: "Nommez le handicap ou la condition",
    },
    RuleLabelEnum.ONLY_IF_GENDER_IDENTITY_RELEVANT: {
        LangType.EN: "Only if gender identity is relevant",
        LangType.DE: "Nur erwähnen, wenn relevant",
        LangType.FR: "Seulement si l'identité de genre est pertinente",
    },
    RuleLabelEnum.NOT_FOR_NON_COMBAT: {
        LangType.EN: "Only use in a combat context",
        LangType.DE: "Nur in einen Kampf-Kontext verwenden",
        LangType.FR: "Utilisez uniquement dans un contexte de combat",
    },
    RuleLabelEnum.ASK_FOR_PREFERENCE: {
        LangType.EN: "Only if preference explicitly stated",
        LangType.DE: "Nur wenn die Person sich so bezeichnet",
        LangType.FR: "Seulement si la préférence est explicitement exprimée",
    },
    RuleLabelEnum.ONLY_WHEN_REFERENCING_RELIGIOUS_PRACTICE: {
        LangType.EN: "Only use in reference to religious practice",
        LangType.DE: "Nur in Bezug auf die religiöse Praxis verwenden",
        LangType.FR: "Utilisez uniquement en référence à la pratique religieuse",
    },
    RuleLabelEnum.USE_IN_TECH_ONLY: {
        LangType.EN: "Use in programming only",
        LangType.DE: "Nur im Programmier-Kontext verwenden",
        LangType.FR: "Utilisez uniquement dans un contexte de programmation",
    },
    RuleLabelEnum.DONT_USE_TO_DESCRIBE_QUALITY: {
        LangType.EN: "Don't use to describe value or quality",
        LangType.DE: "Nicht zur Beschreibung von Wert oder Qualität verwenden",
        LangType.FR: "N'utilisez pas pour décrire la valeur ou la qualité",
    },
    RuleLabelEnum.DONT_USE_FOR_SUBSTANCE_USE: {
        LangType.EN: "Don't use in the context of substance use",
        LangType.DE: "Nicht im Zusammenhang mit Drogenkonsum verwenden",
        LangType.FR: "N'utilisez pas dans le cadre de la consommation de substances",
    },
    RuleLabelEnum.ASK_ABOUT_TRADITIONS: {
        LangType.EN: "Ask about their traditions",
        LangType.DE: "Frage nach ihren Traditionen",
        LangType.FR: "Demandez leurs traditions",
    },
    "ALLGENDER": {
        LangType.EN: "all gender",
        LangType.DE: "Alle Gender",
        LangType.FR: "tous les genres",
    },
    "EMOJIREPETITION": {
        LangType.EN: "Repeating emoji's may exclude screen reader users",
        LangType.DE: "Wiederholen von Emoji kann blinde Menschen ausschließen",
        LangType.FR: "La répétition des emojis peut exclure les utilisateurs·rices de lecteurs d'écran",
    },
    "EMOJISKINTONE": {
        LangType.EN: "Be mindful when using a skin tone that does not match your own",
        LangType.DE: "Vorsicht beim Verwenden von Hauttönen, die nicht den eigenen entsprechen",
        LangType.FR: "Soyez attentif à l'utilisation d'une teinte de peau qui ne correspond pas à la vôtre",
    },
    "EMOJIOVERUSE": {
        LangType.EN: "Emoji overuse may exclude screen reader users",
        LangType.DE: "Übermäßiger Gebrauch von Emoji kann blinde Menschen ausschließen",
        LangType.FR: "L'utilisation excessive d'emojis peut exclure les utilisateurs·rices de lecteurs d'écran",
    },
    "IDENTITYFIRST": {
        LangType.EN: "Identity first",
        LangType.DE: "Identität zuerst",
        LangType.FR: "L'identité d'abord",
    },
    "PERSONFIRST": {
        LangType.EN: "Person first",
        LangType.DE: "Person zuerst",
        LangType.FR: "La personne d'abord",
    },
    "IDENTITYVSPERSONURL": {
        LangType.EN: "https://www.witty.works/en/blog/person-first-vs.-identity-first-understanding-the-approaches",
        LangType.DE: "https://www.witty.works/de/blog/mensch-zuerst-vs.-identit%C3%A4t-zuerst-die-beiden-ans%C3%A4tze-verstehen",
        LangType.FR: "https://www.witty.works/fr/blog/la-personne-dabord-ou-lidentite-dabord",
    },

```

2024-09-19 07:53 UTC, merged

2024-09-23 13:08 UTC, barbaraWittyWorks commented on app/main.py
> +    LangType.FR: [],
LangType.FR: {
    RuleLabelEnum.BE_SPECIFIC: "Soyez précis",
    RuleLabelEnum.NOT_FOR_PEOPLE: "Ne pas utiliser cette expression pour les personnes",
    RuleLabelEnum.NAME_DISABILITY: "Nommer le handicap ou la condition",
    RuleLabelEnum.ONLY_IF_GENDER_IDENTITY_RELEVANT: "Uniquement si l'identité de genre est pertinente",
    RuleLabelEnum.NOT_FOR_NON_COMBAT: "À utiliser uniquement dans un contexte de combat",
    RuleLabelEnum.ASK_FOR_PREFERENCE: "Uniquement si la préférence est explicitement exprimée",
    RuleLabelEnum.ONLY_WHEN_REFERENCING_RELIGIOUS_PRACTICE: "À utiliser uniquement en référence à une pratique religieuse",
    RuleLabelEnum.USE_IN_TECH_ONLY: "À utiliser uniquement dans un contexte de programmation",
    RuleLabelEnum.DONT_USE_TO_DESCRIBE_QUALITY: "Ne pas utiliser pour décrire une valeur ou une qualité",
    RuleLabelEnum.DONT_USE_FOR_SUBSTANCE_USE: "Ne pas utiliser dans le contexte de la consommation de substances",
    RuleLabelEnum.ASK_ABOUT_TRADITIONS: "Demandez à propos de leurs traditions",
},