198 sync false positive
witty-works/nlp_api pull request #245
Opened 2021-12-07 15:10 UTC by Szarad

2021-12-07 15:16 UTC, lsmith77 requested changes

2021-12-07 15:16 UTC, lsmith77 commented on app/main.py
> +else:
feel free to just sent an empty list here as these words were just for Deutsche Bahn

2021-12-07 16:28 UTC, Szarad commented on app/main.py
> +else:
ok, changing

2021-12-07 16:30 UTC, lsmith77 approved these changes

2021-12-07 16:46 UTC, Szarad commented
It is ok that after removing this false-positive list, result from tests/test_false_positive/test_api_corporate_false_positives test with input `{
    "text": "Die Bahn ist stark wegen ihrer Führungskräfte!",
    "config": {
        "store_context": false
    }
}`
 is:
`
E                     ?                 -
E                     +     "results": [
E                     +         {
E                     +             "alternatives": [
E                     +                 "stabil",
E                     +                 "mit Erfahrung",
E                     +                 "fachkundig "
E                     +             ],
E                     +             "category": "unconscious_bias",
E                     +             "context": "",
E                     +             "end": 18,
E                     +             "label": "Sprachliche Voreingenommenheit: Agentisch",
E                     +             "reason": "Unbewusst dem männlichen Geschlecht zugeschrieben. Viele werden davon abgestossen.",
E                     +             "solution": "Teamorientierte Formulierung nutzen oder auf Sinnhaftigkeit einzahlend.",
E                     +             "start": 13,
E                     +             "subcategory": "agentic",
E                     +             "text": "stark"
E                     +         }
E                     +     ]
E                       }
`

 I can update this test with changing false_positive list to empty list? Before that change it was `"results": []` (just empty list)

2021-12-07 16:47 UTC, lsmith77 commented
the test should be adapted to move the old list into redis I guess

2021-12-17 13:06 UTC, Szarad commented on app/main.py
> +false_positive = get_false_positive(gender_false_positive, false_positive_agentic_const)
I had to change global variables terms_false_positive and false_positive_agentic  and wrapped it up in the function  get_false_positive. It was impossible to test getting these variables from redis as they were loaded during import.  Let's discuss on Tuesday refactoring our code to make test easier.

2021-12-20 08:36 UTC, lsmith77 commented on Pipfile.lock
> +                "sha256:0a817b961b46894c5ca8a66b599c745b9a3d9f822725221f0e0fe49dc043a3a3",
did you need to update a dependency? I don't see any changes to the Pipfile itself.

2021-12-20 09:11 UTC, Szarad commented on Pipfile.lock
> +                "sha256:0a817b961b46894c5ca8a66b599c745b9a3d9f822725221f0e0fe49dc043a3a3",
Ah in the end no, I will rebase it

2021-12-20 09:47 UTC, merged