re-add sentry
witty-works/nlp_api pull request #261
Opened 2021-12-15 09:48 UTC by lsmith77

We had Sentry before which I removed because I didn't want to have them in our processors list as their hosting is in the US however we will eventually self-host

2021-12-17 13:41 UTC, Szarad requested changes

2021-12-17 13:41 UTC, Szarad commented on app/sentry.py
> +        return False
this line is causing the problem, sentry_sdk is set to False during testing

2021-12-17 13:46 UTC, Szarad commented on app/sentry.py
> +        return False
We can here `return None` and check the value in main.py in line 439

2021-12-17 13:53 UTC, Szarad requested changes

2021-12-17 13:53 UTC, Szarad commented on app/main.py
> +    sentry_sdk.set_context("request", clean_requestin_data(user_request_in))
```python
if sentry_sdk: 
    sentry_sdk.set_context("request", clean_requestin_data(user_request_in))
 ```

2022-01-04 15:39 UTC, lsmith77 commented on app/sentry.py
> +    if settings.training_data_enabled:
note right now I have not been able to get the posthog integration to work :-/

2022-01-04 15:51 UTC, lsmith77 commented on app/sentry.py
> +    if settings.training_data_enabled:
see also https://github.com/PostHog/posthog-python/issues/46

2022-01-14 13:47 UTC, Szarad approved these changes
Looks good to me

2022-01-14 13:49 UTC, merged