move locale prediction to python
witty-works/nlp_api pull request #316
Opened 2022-01-18 15:51 UTC by lsmith77

fixes https://github.com/witty-works/nlp_api/issues/308

several tests had to be updated since we now prefer `en-US` over `en-GB`

2022-01-20 13:01 UTC, lsmith77 commented on .github/workflows/main.yaml
> -        uses: actions/cache@v1
I switched over to `cache@v2` since only `v2` is able to cache individual files https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows

2022-01-20 13:02 UTC, lsmith77 commented on README.md
> +wget -P training_data https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin
this will also need to be added to the Docker setup

2022-01-20 19:43 UTC, Szarad requested changes

2022-01-20 19:43 UTC, Szarad commented on app/models.py
> +        if isinstance(v, str) and v != "":
validator is not working after changing type of class attribute (from str to List)
can be rewrite to:
```
if isinstance(v, list) and v != []:
    for lang in v:
        if lang not in Config._supported_locales:
            raise ValueError("Contains not supported preferred_variants: %s" % lang)
    return v
```

2022-01-20 19:43 UTC, Szarad commented on app/models.py
> +        if isinstance(v, str) and v != "":
validator not working, `v` is a List now
Can be rewrite to:
```
if isinstance(v, list) and v != []:
    for lang in v:
        if lang not in Config._supported_langs:
            raise ValueError("Contains not supported preferred_languages: %s" % lang)
    return v
```

2022-01-20 19:43 UTC, Szarad commented on app/models.py
> +        if isinstance(v, str) and v != "":
validator not working, the same as above

2022-01-20 19:43 UTC, Szarad commented on app/models.py
> +        if isinstance(v, str) and v != "":
Validator is not working, because `v` is a List now, the same as above

2022-01-21 07:37 UTC, lsmith77 commented on app/models.py
> +        if isinstance(v, str) and v != "":
I fixed it so that it now supports both strings (comma separated) and lists

2022-01-21 08:22 UTC, Szarad approved these changes
Tested, looks good from my side.

2022-01-21 08:23 UTC, merged