merge the rule analysis and ignore.txt update scripts
witty-works/nlp_api pull request #366
Opened 2022-02-03 13:11 UTC by lsmith77

fixes https://github.com/witty-works/nlp_api/issues/358

2022-02-08 21:14 UTC, Szarad requested changes
After I changed LanguageTool server check, all works good on my side.

2022-02-08 21:14 UTC, Szarad commented on README.md
> +pipenv run python -m analyze_rules -l English
should be -l `en`

2022-02-08 21:14 UTC, Szarad commented on analyze_rules.py
> +        response = requests.get(api_url)
Scripts for generating ignore stops here, because it get 400 from languagetool `An error has occurred: 'Missing 'text' or 'data' parameter'` We can check get from v2/languages endpoint as we do in health probe: `response = requests.get(api_url.rstrip("/check") + "/languages")`

2022-02-09 07:34 UTC, lsmith77 commented on README.md
> +pipenv run python -m analyze_rules -l English
fixed

2022-02-09 07:34 UTC, lsmith77 commented on analyze_rules.py
> +        response = requests.get(api_url)
fixed

2022-02-09 08:04 UTC, Szarad approved these changes
I tested the changes, all good!

2022-02-09 08:06 UTC, merged