massdriver
witty-works/nlp_api pull request #738
Opened 2023-01-31 20:43 UTC by lsmith77

https://md.witty.works/

2023-03-22 17:00 UTC, likelymichael commented on massdriver-lang/schema-artifacts.json
> +{
These schema-*.json files are for local development, and don't need to be checked into a repo. They can be added to your `.gitignore` file.

2023-03-22 17:01 UTC, likelymichael commented on massdriver-lang/src/_params.auto.tfvars.json
> +{
The _connections*, _params*, and _md* files can also be added to your `.gitignore` file.

2023-03-22 17:02 UTC, likelymichael reviewed
Added some context to files that can be added to `.gitignore` file so they're not checked into repo.

2023-03-28 17:19 UTC, likelymichael commented on Dockerfile
> +WORKDIR /code
```suggestion

WORKDIR /code
```
`WORKDIR` will create the directory for you if it doesn't exist, so the `RUN mkdir` layer is not needed

2023-03-28 17:22 UTC, likelymichael commented on Dockerfile
> +USER appuser
If these are moved up to L20 above `WORKDIR`, then you wouldn't need to set folder permissions w/ `chown`

2023-03-28 17:23 UTC, likelymichael commented on massdriver/src/main.tf
> +  additional_envs    = []
```suggestion
```
We can remove this array, we aren't using this anymore (has been updated in our app template).

2023-03-28 17:24 UTC, likelymichael commented on massdriver-lang/src/main.tf
> +  additional_envs    = []
```suggestion
```
We can remove this array, we aren't supporting it anymore and it's been updated in our app templates.

2023-03-28 17:25 UTC, likelymichael requested changes
Some formatting changes recommended for Dockerfile and helm chart

2023-04-22 10:32 UTC, lsmith77 commented on Dockerfile
> +# TODO compute WORKER = (CPU * 2 * MULTIPLIER) + 1
@chrisghill ideally we compute the worker count here based on the formula above. I guess this should happen inside the `massdriver.yaml` ?

2023-04-26 17:10 UTC, chrisghill commented on Dockerfile
> +# TODO compute WORKER = (CPU * 2 * MULTIPLIER) + 1
Hey @lsmith77 , sorry I didn't see this until now.

If the worker count can be set via an environment variable, then I would recommend doing it in `massdriver.yaml`.  It's up to you whether you want to specify a safe default in the Dockerfile (`ENV WORKERS 4`). The only benefit here would be if you wanted your image to be able to be run without *requiring* setting the `WORKERS` env.

Environment variables set at runtime will override values set in a Dockerfile., so in `massdriver.yaml` you could have

```
app:
  envs:
    WORKERS: (.params.resourceRequests.cpu * 2 * .params.configuration.multiplier) | ceil | tostring
```

This obviously requires you have a field named `multiplier` in your `params.configuration` block.  The `ceil` and `tostring` are important to make sure you get an integer, and convert it into a string since all environment variables need to be strings.

2023-04-27 11:24 UTC, lsmith77 commented on Dockerfile
> +# TODO compute WORKER = (CPU * 2 * MULTIPLIER) + 1
@chrisghill ok great thx. is there some way to view the computed final environment variable values?

2023-04-27 11:28 UTC, lsmith77 commented on Dockerfile
> +# TODO compute WORKER = (CPU * 2 * MULTIPLIER) + 1
here is my attempt at implementing your suggestion https://github.com/witty-works/nlp_api/pull/738/commits/8e4c4b15d343fdc0492710ecde624939b8c111a0

2023-04-27 17:23 UTC, chrisghill commented on Dockerfile
> +# TODO compute WORKER = (CPU * 2 * MULTIPLIER) + 1
You can use `kubectl` to `describe` either a pod or the deployment. This should give you a list of the environment variables.  For example:

```
$ kubectl describe pod nlpapi-main-nlpapi-5t4h-6f9659f9d8-fv544
Name:         nlpapi-main-nlpapi-5t4h-6f9659f9d8-fv544
Namespace:    default
...
    Environment:
      LANGS:                      ["en","de"]
      LOGGING_CONFIG_FILENAME:    stdout
      LOGGING_ENABLED:            true
      REDIS_PORT:                 6380
...
```

I pruned a bulk of the values (particularly sensitive values), but that gives you an idea.

2023-05-05 16:57 UTC, likelymichael approved these changes
Other than the `locales` directory needing to be removed from the `Dockerfile`, the rest looks great! Left some informational comments about GitHub actions and how they can be utilized for different branches/environments.

2023-05-05 16:57 UTC, likelymichael commented on .github/workflows/deployAzure.yaml
> +    branches: [feature/massdriver]
When this gets merged to `main`, this trigger should be updated to where you want it to be. Do you have a `dev` branch as well? If so, creating 2 GitHub actions (1 for prod, 1 for staging) is a great way to test changes in staging before merging to prod.

2023-05-05 16:57 UTC, likelymichael commented on .github/workflows/deployAzure.yaml
> +          project: nlpapi
If you do set up 2 GitHub actions, the `Set Image Version` and `Deploy App` steps will need to be updated to match the values for your other environment.

2023-05-05 16:57 UTC, likelymichael commented on Dockerfile
> +COPY ./locales /code/locales
No `locales` directory in repo.

2023-05-12 12:36 UTC, lsmith77 commented on .github/workflows/deployAzure.yaml
> +    branches: [feature/massdriver]
yeah .. we do have `dev`

isn't it possible to have a single GA to prevent differences between the two to cause problems.

shouldn't changing `target: main` to `target: github.ref_name` do the trick? that being said .. for prod releases I would technically prefer to use a git tag and not the `main` branch

@chrisghill do you have some advice here?

2023-05-12 12:40 UTC, lsmith77 commented on Dockerfile
> +CMD gunicorn app.main:app --preload -b 0.0.0.0:8081 -w 1 -k uvicorn.workers.UvicornWorker --forwarded-allow-ips "*"
@chrisghill if I use `-w $WORKERS` here I end up getting

```
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: argument -w/--workers: expected one argument
```

2023-05-15 18:00 UTC, likelymichael commented on .github/workflows/deployAzure.yaml
> +    branches: [feature/massdriver]
> shouldn't changing target: main to target: github.ref_name do the trick? that being said .. for prod releases I would technically prefer to use a git tag and not the main branch

the `target:main` on lines 58 and 67 reference your application on massdriver. the `project`, `target`, and `manifest` fields merge together to create the slug used to designate which application to publish/deploy.

> isn't it possible to have a single GA to prevent differences between the two to cause problems.

you could set conditionals within a single github action to run `patch`/`publish`/`deploy` on all of your apps, but it could become daunting to manage as you scale

2023-05-15 23:29 UTC, chrisghill commented on .github/workflows/deployAzure.yaml
> +    branches: [feature/massdriver]
GHA does support using conditionals (https://docs.github.com/en/actions/learn-github-actions/expressions), however I find that writing, reading and managing a single workflow file with multiple conditionals for different environments is much more overhead than simply maintaining 2 separate workflow files. I've always maintained a separate file for each environment.

As Michael mentioned, the `target` field is referencing the Massdriver "environment" (previously called "target"). 
![image](https://github.com/witty-works/nlp_api/assets/15616541/5f425397-bbdb-46b7-aae7-c439b5b932a8)

2023-05-16 05:31 UTC, chrisghill commented on Dockerfile
> +CMD gunicorn app.main:app --preload -b 0.0.0.0:8081 -w 1 -k uvicorn.workers.UvicornWorker --forwarded-allow-ips "*"
So in a Dockerfile, [an `ARG` is an "internal" variable used for image building purposes](https://docs.docker.com/engine/reference/builder/#arg), it doesn't persist beyond the building process.  For example, we do this in one of our images:

```
ARG BASE_IMG=golang:1.18

FROM ${BASE_IMG} as base
...
```

This basically makes the image a "build-time variable" that can easily be changed at the top of the file.  You'll noticed it's referenced with `${...}`.  So if you did:

```
ARG WORKERS=1
CMD gunicorn app.main:app --preload -b 0.0.0.0:8081 -w ${WORKERS} -k uvicorn.workers.UvicornWorker --forwarded-allow-ips "*"
```

It should work, but this still isn't what you want. You're effectively "hardcoding" the number of workers in the image. You want to variable-ize it via an environment variable.

```
ENV WORKERS=1
CMD gunicorn app.main:app --preload -b 0.0.0.0:8081 -w $WORKERS -k uvicorn.workers.UvicornWorker --forwarded-allow-ips "*"
```

This will make it so the number of workers is determined by the `WORKERS` environment variable, which is defaulted to `1`, but can be overridden at image run time by setting that environment variable to something else.

2023-05-16 11:08 UTC, merged